[tool.poetry]
name = "cvxportfolio"
version = "0.1.0"
description = "..."
authors = ["Cvxportfolio's Contributors"]
readme = "README.md"
repository = "https://github.com/cvxgrp/cvxportfolio"
homepage = "https://cvxportfolio.readthedocs.io"
packages = [{include = "cvxportfolio"}]

[tool.poetry.dependencies]
python = ">=3.9.0"
qdldl = ">=0.1.7"
pandas = "*"
numpy = "*"
cvxpy = "*"
multiprocess = "*"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-cov = "*"
matplotlib = "*"
yfinance = "*"
pandas_datareader = "*"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
