[tool.poetry]
name = "cvxportfolio"
version = "0.0.1"
description = "..."
authors = ["Enzo Buseti", "Steven Diamond", "Stephen Boyd"]
readme = "README.md"
repository = "https://github.com/cvxgrp/cvxportfolio"
packages = [{include = "cvxportfolio"}]

[tool.poetry.dependencies]
python = ">=3.9.0"
pandas = "*"
numpy = "*"
#matplotlib = "*"
cvxpy = "*"
multiprocess = "*"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-cov = "*"
matplotlib = "*"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
