package:
  name: cvxportfolio
  version: "0.0.5"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
  run:
    - python
    - pandas
    - numpy
    - matplotlib
    - cvxpy >=1.0.6

test:
  imports:
    - cvxportfolio
    - cvxportfolio.tests
    - cvxportfolio.utils
  requires:
    - nose
  commands:
    - nosetests cvxportfolio

about:
  home: http://github.com/cvxgrp/cvxportfolio/
  license: Apache
  license_family: APACHE
  summary: Portfolio optimization and simulation in Python.
  doc_url: 'http://cvxportfolio.org'
  dev_url: 'http://github.com/cvxgrp/cvxportfolio/'

extra:
  recipe-maintainers: 'Enzo Busseti'
